# Generated by Django 5.0.4 on 2024-04-29 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_instructions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('metric', models.CharField(choices=[('GRAMS', 'GRAMS'), ('LITERS', 'LITERS'), ('TEASPOONS', 'TEASPOONS'), ('TABLESPOONS', 'TABLESPOONS'), ('CUPS', 'CUPS'), ('OUNCES', 'OUNCES'), ('POUNDS', 'POUNDS'), ('KILOGRAMS', 'KILOGRAMS'), ('MILLITTERS', 'MILLITTERS'), ('UNITS', 'UNITS'), (' ', ' ')], default=' ', max_length=50)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipe.category')),
            ],
        ),
    ]
